### ISSUE TITLE
Tooling for automated flashing

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/mch2022-project#17]
Build tooling for automatically flashing badges.

Consists of two parts:

1. Flashing the RP2040: the badge initially shows up in the form of the RP2040 ROM bootloader. This bootloader has it's own usb vid/pid pair. When such a device is connected picotool should be called to flash the UF2 file with the co-processor firmware. Ask Renze for a development version of this file.

2. Flashing the ESP32: after flashing the co-processor firmware the badge shows up as mch2022 badge. In this state the ESP32 firmware can be loaded onto the device via esptool.py.
 - Should flash bootloader
 - Should flash phy init data
 - Should flash OTA data initial
 - Should flash launcher firmware to OTA 0 partition
 - Should flash prepared AppFS partition data to preload Sponsors reel app, Python & native apps built by sponsors
 - Should flash prepared FAT partition data to preload apps built by sponsors in Python as well as metadata for the preinstalled native apps

**Comment by Pwuts** [comment]
https://github.com/badgeteam/mch2022-autoflasher
