### ISSUE TITLE
Cost reduction

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/mch2022-project#3]
Ideas for reducing costs:

 - Get rid of the IO expander by removing SPI from the RP2040 and connecting the buttons there
 - Get rid of the separate power switch for the LEDs and use the SD card power rail instead (saves 1 IO pin on the RP2040, also the RP2040 SPI CS line on the ESP32 can be used for LED data, saving another IO pin on the RP2040).

Please add your ideas as comments :-), think about even simple things like resistors we don't need and such.

**Comment by kliment** [comment]
PCM5100 is not available most places and has doubled in price at the places where it is available. Consider replacing with another DAC, for example this 16 bit stereo DAC https://lcsc.com/product-detail/Digital-To-Analog-Converters-DACs_TM-Shenzhen-Titan-Micro-Elec-TM8211_C92003.html

**Comment by kliment** [comment]
All the buttons can go on a single ADC pin by using a resistor array to make them all generate a different voltage.

**Comment by Mecrisp** [comment]
Another idea is to use a charlieplexing setup, and add a diode to each button. Then by using the internal pullup/pulldowns one can check for buttons individually, given that the voltage drop of the diodes is detectable as logic level.
![3-pin_Charlieplexing_with_common_resistors svg](https://user-images.githubusercontent.com/17645178/155627078-36a705c3-000d-43fc-a895-1a63ef27a23b.png)
This is for three GPIO pins that can cater for 6 buttons, with 4 GPIO lines 12 buttons can be read.
