### ISSUE TITLE
FPGA factory test bitstream

### ISSUE THREAD

**Issue by ranzbak** [badgeteam/mch2022-project#6]
A bitstream that can be loaded by the initial ESP firmware, so the factory workers in China can check the badges in the factory.
Since the production date is before the MCH event, this bitstream has priority :-)

The result of the test should go to the ESP 32, that can display on the LCD an error message, indicating the hardware failure (if any).

Factory test
————————————-
 - test pattern to the LCD
 - test pattern to the led (blink RGB?)
 - Toggle interrupt pint slowly  (10x per second?) high/low
 - Do  PSRAM self test
 - Do SPI echo with first byte replaced by status of self test (Or a better alternative way of testing SPI and reporting status)
 - Do test pattern on PMOD (one pin at a time low?)
 -  UART connection to FPGA from RP2040 (send message ?)

**Comment by smunaut** [comment]
# Proposed functionality

General idea is that the FPGA offers functions to the ESP32 for testing, but the ESP32 is running the show.

* SPI:
    - Implements the protocol described previously
    - A few "hardware" commands
        - An ECHO command: To allow signal integrity checks at high rate
        - An LCD command: To send data to the LCD quickly
    - The rest are just interpreted by the soft RISC-V (see below for commands needed)
* UART:
    - By default it's the RISC-V firmware console @ 1 Mbaud
    - One of the console command is 'e' (echo) and will echo whatever string ('\n' terminated) with the case of A-Z inverted.
    - So this should allow to check those wires are connected, not shorted (case-swap) and no bad contact (operating at highish speed)
* PMOD:
    - Controlled by a GPIO block driven by RISC-V
    - By default going in sequence outputing a 0 or Z.
    - Should show up on a 8 led pmod, and we can also confirm no-shorts by probing the 'Z' ones and checking they are pulled up.
    - Can be set/get to any value by SPI command
* PSRAM:
    - Memtest triggered by SPI command from ESP32
    - ESP32 can also read the test result to know if it passed
* RGB led:
    - Wired to `SB_LEDDA_IP` driven by RISC-V
    - Set by default to breathing pale blue (a bit of each color, but more blue)
    - Can be set to any supported color / pattern by SPI command from the ESP32
    - Should be changed to constant white when OK (to visually confirm all dies work)
* LCD:
    - By default doesn't do anything
    - Upon command from the ESP32, will take over, execute reset and re-init and display color bars
    - A fast path from SPI to LCD also exists so that the ESP32 can display the final test results to the LCD through FPGA
    - A counter of the number of FMARK received is also readable by ESP32 to confirm this works at the expected rate
* Interrupt:
    - GPIO line controlled by the ESP32 that can set it and chek the expected value is read back

Typically a sequence run by the ESP32 would be something like :
 - Load FPGA
 - Execute SPI loopback test to check SPI works (needed for the rest)
 - Request the RP2040 to check UART echo
 - Request the FPGA test PSRAM (and readback result)
 - Request the PMOD check results

Those are all the "automatic test". Then some test need some level of user interaction / checking :
 - Request led to constant white and user checks all dies are OK.
 - User plugs in 8 LED PMOD to check they sequence correctly ?
 - Request the FPGA to take over the LCD, display color bar, then 1 sec later, ask the user if he saw them.
 - From the point above, the ESP can draw the screen through the FPGA ( to test it more ), to display the final pass/fail for instance
