### ISSUE TITLE
ESP32 self test functionality

### ISSUE THREAD

**Issue by ranzbak** [badgeteam/mch2022-project#9]
Functionality that is part of the factory flash firmware that checks the hardware connected to the ESP32

This includes 
------------------
- The LCD
- RP2040
- FPGA check over SPI (coordinate with FPGA team to agree on a communication protocol https://github.com/badgeteam/mch2022-project/issues/6)
- Test buttons / joystick
- SD-Card
- USB ?
- LEDs ?

When the test is done a result should be shown on the badge LCD, or the green LED's should blink if the LCD is broken

Please add stuff I missed to this ticket

**Comment by renzenicolai** [comment]
I am going to move this to the ESP32 firmware repository
